networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build:
      target: prod
    ports:
      - "4200:80"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/web
    networks:
      - frontend
  
  bugboard:
    develop:
      watch:
        - action: rebuild
          path: ./backend/bugboard
    networks:
      - backend
 
  users:
    develop:
      watch:
        - action: rebuild
          path: ./backend/users
    networks:
      - backend