volumes:
  BugBoard26-frontend-web-node-modules:
  BugBoard26-frontend-web-angular-cache:
  BugBoard26-backend-maven-repo:

services:
  # --- FRONTEND ---
  web:
    profiles: []  
    extends:
      file: "compose.base.yaml"
      service: web
    build:
      target: localdev
    volumes:
      - .:/BugBoard26
      - BugBoard26-frontend-web-node-modules:/BugBoard26/frontend/web/node_modules:rw
      - BugBoard26-frontend-web-angular-cache:/BugBoard26/frontend/web/.angular:rw

# --- BACKEND: USERS ---
  users:
    profiles: []
    build:
      context: ./backend/users
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/users/.env
    volumes:
      - ./backend/users:/BugBoard26/backend/users
      - BugBoard26-backend-maven-repo:/root/.m2

  # --- BACKEND: BUGBOARD ---
  bugboard:
    profiles: []
    build:
      context: ./backend/bugboard
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/bugboard/.env
    volumes:
      - ./backend/bugboard:/BugBoard26/backend/bugboard
      - BugBoard26-backend-maven-repo:/root/.m2
