networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build:
      target: prod
    ports:
      - "4200:80"
    networks:
      - frontend
  
  bugboard:
    networks:
      - backend
 
  users:
    networks:
      - backend