name: bugboard26

services:
  docs:
    build:
      context: ./docs
      dockerfile: ./Dockerfile
    profiles:
      - docs

  web:
    profiles:
      - web
      - frontend
      - fullstack

  bugboard:
    profiles:
      - bugboard
      - backend
      - fullstack

  users:
    profiles:
      - users
      - backend
      - fullstack

